
from exception.common import CustomException


class ServiceException(CustomException):
    pass

